CREATE TABLE tb_movie (
  id INTEGER NOT NULL AUTO_INCREMENT,
  title VARCHAR NOT NULL,
  winner VARCHAR NULL DEFAULT NULL,
  producer VARCHAR NOT NULL,
  studio VARCHAR NOT NULL,
  year INTEGER (11) NOT NULL,
  PRIMARY KEY (id));

